name: opan
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - gensim
  - nltk
  - numpy
  - matplotlib
  - scikit-learn
  - scipy
  - sympy
  - pandas
  - seaborn
  - bokeh
  - lxml
